### PR TITLE
Fixes for artist missing under album lists and on the main page.

### PR DESCRIPTION
**Pull request by evilhamster**
This sorts the problems in library -> album and on the main page. 

What do you think about trying to hunt down all the:
StringUtils::Join(_Artist_, g_advancedSettings.m_musicItemSeparator) and replace them with the Desc fields instead?

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks @evilhamster . I have been working on similar changes myself, as yet not commited. What do they say about great minds?

On the road today, but will get into this soonest.

**Comment by DaveTBlake** [comment]
@evilhamster just doing a rebase, need to check things over too. Don't waste time on testing my efforts until we have had a chat :)

Are there possible problems with using CMusicInfoTag::GetArtistDesc in all the places that have something like StringUtils::Join(tag->GetArtist(), g_advancedSettings.m_musicItemSeparator)?

I like the idea of using the desc string, but I am mindful that since ARTISTS tag the artists (in artist credits vector and song_artist table) can be different from the description string (in song table strArtists, CSong.strArtistDesc). Also if tag is populated by artist vector the ArtistDesc does not get filled. So we need to be mindful of what we are passing.

**Comment by evilhamster** [comment]
Will do!

There are probably potential problems, but I think they are less than not doing it :)

Isn't that the point that information in the artist vector and the descriptive string should be different? 

The more I have been thinking about, the less pleased I am with the naming of the "Desc" variable. We could do the following:

rename the desc functions to something like:
GetArtistDesc -> GetArtistString

If we have a manually set artiststring, we return that one if we don't have it we do a join of contents in the vector. We should also probably create functions to get this information for song/album/tag and move the variables into the private space of the classes. If we did this, I think it would be kind of straight forward. What do you think?

Let me know if when you are closer to getting something to work or if you would like me to work in something in regards to this!

**Comment by DaveTBlake** [comment]
I agree with your thinking, that is the kind of change I have been making. :)

> Isn't that the point that information in the artist vector and the descriptive string should be different?

There may be some cases where it is not clear which is appropriate for the processing - the actual artist names as a string, or the user's description of them. I have possibly been inconsistent in my changes so I want to go back through it.

Any chance of you looking at PR8011 and the loss of tag scanning on the fly from file view? As usual I am having problems with building my rebase...

**Comment by evilhamster** [comment]
I spent some time tracking down the cause of it (rebuilding a lot of different versions to be able to find which pr introduced the problem was sooooo fun), but haven't actually spent any time on fixing that problem (I consider it a problem until we can offer the same functionality in some other way).

**Comment by DaveTBlake** [comment]
I bet it took ages, well it would have me. Well done for that and thanks on behalf of us all. :)

The fix belongs in CGUIViewStateWindowMusicNav creator, that  is now where the UI comes from.  Needs some addsort calls when the files are tagged (not folders), but the video stuff around line 465 looks odd too - why test video not music - yet it has been there a long time.

But we digress....

**Comment by DaveTBlake** [comment]
New commit (and rebase) just to show I have been working too :)
I'm going to take another long look tomorrow, probably squish too, but have a look if you have time.

**Comment by DaveTBlake** [comment]
@evilhamster just a heads up that I am having a look at the inadvertant fileview display changes that PR8011 has produced. Doing the easy bit after all your hard work locating the cause :)

Have a look in my branch to see how I am getting on.

**Comment by DaveTBlake** [comment]
Finally got back to tidy up CSong and CAlbum by removing artist vector. Have rebased and squished  8158. Hope you can find some time to check it over.

I noticed that a bit of my more artists than MBID change had crept in accidentally, so I have taken that out. Not trying to sneek things past you!! I am happy to drop that change, just wondered if anyone else has a deciding opinion.

**Pull request closed without merging**
